### ISSUE TITLE
bash build-ventus.sh构建出错

### ISSUE THREAD

**Issue by nwy2010** [THU-DSP-LAB/llvm-project#120]
llvm-spirv: LLVM_SPIRV-NOTFOUND

BUILDING riscv32--
        DEVICE: none (  )
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_LLAsm_COMPILER_WORKS

-- Build files have been written to: /home/wuyang.nie/projects/ventus/llvm-project/build-libclc
[3/11] Building CLC object CMakeFiles/builtins.link.riscv32--.dir/riscv32/lib/compiler-rt/nextafterf.bc
FAILED: CMakeFiles/builtins.link.riscv32--.dir/riscv32/lib/compiler-rt/nextafterf.bc 
/home/wuyang.nie/projects/ventus/llvm-project/install/bin/clang -DCLC_RISCV32 -D__CLC_INTERNAL -I/home/wuyang.nie/projects/ventus/llvm-project/install/include -I/home/wuyang.nie/projects/ventus/llvm-project/libclc/generic/include -target riscv32 -mcpu=ventus-gpgpu -cl-std=CL2.0 -I/home/wuyang.nie/projects/ventus/llvm-project/libclc/generic/include -Dcl_khr_fp64  -ffunction-sections -fdata-sections -cl-no-stdinc -target riscv32-- -fno-builtin -nostdlib -I /home/wuyang.nie/projects/ventus/llvm-project/libclc/riscv32/lib/compiler-rt -o CMakeFiles/builtins.link.riscv32--.dir/riscv32/lib/compiler-rt/nextafterf.bc -c /home/wuyang.nie/projects/ventus/llvm-project/libclc/riscv32/lib/compiler-rt/nextafterf.cl -emit-llvm && /home/wuyang.nie/projects/ventus/llvm-project/install/bin/clang -DCLC_RISCV32 -D__CLC_INTERNAL -I/home/wuyang.nie/projects/ventus/llvm-project/install/include -I/home/wuyang.nie/projects/ventus/llvm-project/libclc/generic/include -target riscv32 -mcpu=ventus-gpgpu -cl-std=CL2.0 -I/home/wuyang.nie/projects/ventus/llvm-project/libclc/generic/include -Dcl_khr_fp64  -ffunction-sections -fdata-sections -cl-no-stdinc -target riscv32-- -fno-builtin -nostdlib -I /home/wuyang.nie/projects/ventus/llvm-project/libclc/riscv32/lib/compiler-rt -o CMakeFiles/builtins.link.riscv32--.dir/riscv32/lib/compiler-rt/nextafterf.bc.o -c /home/wuyang.nie/projects/ventus/llvm-project/libclc/riscv32/lib/compiler-rt/nextafterf.cl && /home/wuyang.nie/projects/ventus/llvm-project/install/bin/clang -DCLC_RISCV32 -D__CLC_INTERNAL -I/home/wuyang.nie/projects/ventus/llvm-project/install/include -I/home/wuyang.nie/projects/ventus/llvm-project/libclc/generic/include -target riscv32 -mcpu=ventus-gpgpu -cl-std=CL2.0 -I/home/wuyang.nie/projects/ventus/llvm-project/libclc/generic/include -Dcl_khr_fp64  -ffunction-sections -fdata-sections -cl-no-stdinc -target riscv32-- -fno-builtin -nostdlib -I /home/wuyang.nie/projects/ventus/llvm-project/libclc/riscv32/lib/compiler-rt -o CMakeFiles/builtins.link.riscv32--.dir/riscv32/lib/compiler-rt/nextafterf.bc.s -S  /home/wuyang.nie/projects/ventus/llvm-project/libclc/riscv32/lib/compiler-rt/nextafterf.cl && /home/wuyang.nie/projects/ventus/llvm-project/install/bin/clang -DCLC_RISCV32 -D__CLC_INTERNAL -I/home/wuyang.nie/projects/ventus/llvm-project/install/include -I/home/wuyang.nie/projects/ventus/llvm-project/libclc/generic/include -target riscv32 -mcpu=ventus-gpgpu -cl-std=CL2.0 -I/home/wuyang.nie/projects/ventus/llvm-project/libclc/generic/include -Dcl_khr_fp64  -ffunction-sections -fdata-sections -cl-no-stdinc -target riscv32-- -fno-builtin -nostdlib -I /home/wuyang.nie/projects/ventus/llvm-project/libclc/riscv32/lib/compiler-rt -o CMakeFiles/builtins.link.riscv32--.dir/riscv32/lib/compiler-rt/nextafterf.bc.ll -S -emit-llvm /home/wuyang.nie/projects/ventus/llvm-project/libclc/riscv32/lib/compiler-rt/nextafterf.cl && /home/wuyang.nie/projects/ventus/llvm-project/install/bin/clang -DCLC_RISCV32 -D__CLC_INTERNAL -I/home/wuyang.nie/projects/ventus/llvm-project/install/include -I/home/wuyang.nie/projects/ventus/llvm-project/libclc/generic/include -target riscv32 -mcpu=ventus-gpgpu -cl-std=CL2.0 -I/home/wuyang.nie/projects/ventus/llvm-project/libclc/generic/include -Dcl_khr_fp64  -ffunction-sections -fdata-sections -cl-no-stdinc -target riscv32-- -fno-builtin -nostdlib -I /home/wuyang.nie/projects/ventus/llvm-project/libclc/riscv32/lib/compiler-rt -o CMakeFiles/builtins.link.riscv32--.dir/riscv32/lib/compiler-rt/nextafterf.bc.o -c /home/wuyang.nie/projects/ventus/llvm-project/libclc/riscv32/lib/compiler-rt/nextafterf.cl && /home/wuyang.nie/projects/ventus/llvm-project/install/bin/clang -DCLC_RISCV32 -D__CLC_INTERNAL -I/home/wuyang.nie/projects/ventus/llvm-project/install/include -I/home/wuyang.nie/projects/ventus/llvm-project/libclc/generic/include -target riscv32 -mcpu=ventus-gpgpu -cl-std=CL2.0 -I/home/wuyang.nie/projects/ventus/llvm-project/libclc/generic/include -Dcl_khr_fp64  -ffunction-sections -fdata-sections -cl-no-stdinc -target riscv32-- -fno-builtin -nostdlib -I /home/wuyang.nie/projects/ventus/llvm-project/libclc/riscv32/lib/compiler-rt  -o CMakeFiles/builtins.link.riscv32--.dir/riscv32/lib/compiler-rt/nextafterf.bc.h -E /home/wuyang.nie/projects/ventus/llvm-project/libclc/riscv32/lib/compiler-rt/nextafterf.cl
clang: /home/wuyang.nie/projects/ventus/llvm-project/llvm/include/llvm/CodeGen/MachineOperand.h:360: llvm::Register llvm::MachineOperand::getReg() const: Assertion `isReg() && "This is not a register operand!"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.      Program arguments: /home/wuyang.nie/projects/ventus/llvm-project/install/bin/clang -DCLC_RISCV32 -D__CLC_INTERNAL -I/home/wuyang.nie/projects/ventus/llvm-project/install/include -I/home/wuyang.nie/projects/ventus/llvm-project/libclc/generic/include -target riscv32 -mcpu=ventus-gpgpu -cl-std=CL2.0 -I/home/wuyang.nie/projects/ventus/llvm-project/libclc/generic/include -Dcl_khr_fp64 -ffunction-sections -fdata-sections -cl-no-stdinc -target riscv32-- -fno-builtin -nostdlib -I /home/wuyang.nie/projects/ventus/llvm-project/libclc/riscv32/lib/compiler-rt -o CMakeFiles/builtins.link.riscv32--.dir/riscv32/lib/compiler-rt/nextafterf.bc.o -c /home/wuyang.nie/projects/ventus/llvm-project/libclc/riscv32/lib/compiler-rt/nextafterf.cl
1.      <eof> parser at end of file
2.      Code generation
3.      Running pass 'Function Pass Manager' on module '/home/wuyang.nie/projects/ventus/llvm-project/libclc/riscv32/lib/compiler-rt/nextafterf.cl'.
4.      Running pass 'Ventus load instruction legalization pass' on function '@__nextafter'
 #0 0x00007f72bcaec94e llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) /home/wuyang.nie/projects/ventus/llvm-project/llvm/lib/Support/Unix/Signals.inc:567:22
 #1 0x00007f72bcaeca09 PrintStackTraceSignalHandler(void*) /home/wuyang.nie/projects/ventus/llvm-project/llvm/lib/Support/Unix/Signals.inc:641:1
 #2 0x00007f72bcaea614 llvm::sys::RunSignalHandlers() /home/wuyang.nie/projects/ventus/llvm-project/llvm/lib/Support/Signals.cpp:104:20
 #3 0x00007f72bcaec16f llvm::sys::CleanupOnSignal(unsigned long) /home/wuyang.nie/projects/ventus/llvm-project/llvm/lib/Support/Unix/Signals.inc:366:31
 #4 0x00007f72bc9341f7 (anonymous namespace)::CrashRecoveryContextImpl::HandleCrash(int, unsigned long) /home/wuyang.nie/projects/ventus/llvm-project/llvm/lib/Support/CrashRecoveryContext.cpp:77:5
 #5 0x00007f72bc934772 CrashRecoverySignalHandler(int) /home/wuyang.nie/projects/ventus/llvm-project/llvm/lib/Support/CrashRecoveryContext.cpp:398:1
 #6 0x00007f72bc231090 (/lib/x86_64-linux-gnu/libc.so.6+0x43090)
 #7 0x00007f72bc23100b raise /build/glibc-e2p3jK/glibc-2.31/signal/../sysdeps/unix/sysv/linux/raise.c:51:1
 #8 0x00007f72bc210859 abort /build/glibc-e2p3jK/glibc-2.31/stdlib/abort.c:81:7
 #9 0x00007f72bc210729 get_sysdep_segment_value /build/glibc-e2p3jK/glibc-2.31/intl/loadmsgcat.c:509:8
#10 0x00007f72bc210729 _nl_load_domain /build/glibc-e2p3jK/glibc-2.31/intl/loadmsgcat.c:970:34
#11 0x00007f72bc221fd6 (/lib/x86_64-linux-gnu/libc.so.6+0x33fd6)
#12 0x00007f72c7758450 llvm::MachineOperand::getReg() const /home/wuyang.nie/projects/ventus/llvm-project/llvm/include/llvm/CodeGen/MachineOperand.h:360:5
#13 0x00007f72c78a654d (anonymous namespace)::VentusLegalizeLoad::checkInstructionUse(llvm::MachineBasicBlock&, llvm::MachineInstr&) /home/wuyang.nie/projects/ventus/llvm-project/llvm/lib/Target/RISCV/VentusLegalizeLoad.cpp:176:66
#14 0x00007f72c78a65c5 (anonymous namespace)::VentusLegalizeLoad::checkInstructionUse(llvm::MachineBasicBlock&, llvm::MachineInstr&) /home/wuyang.nie/projects/ventus/llvm-project/llvm/lib/Target/RISCV/VentusLegalizeLoad.cpp:177:15
#15 0x00007f72c78a627f (anonymous namespace)::VentusLegalizeLoad::checkVLWDependency(llvm::MachineBasicBlock&, llvm::MachineInstr&) /home/wuyang.nie/projects/ventus/llvm-project/llvm/lib/Target/RISCV/VentusLegalizeLoad.cpp:149:17
#16 0x00007f72c78a60f1 (anonymous namespace)::VentusLegalizeLoad::runOnMachineBasicBlock(llvm::MachineBasicBlock&) /home/wuyang.nie/projects/ventus/llvm-project/llvm/lib/Target/RISCV/VentusLegalizeLoad.cpp:131:20
#17 0x00007f72c78a6015 (anonymous namespace)::VentusLegalizeLoad::runOnMachineFunction(llvm::MachineFunction&) /home/wuyang.nie/projects/ventus/llvm-project/llvm/lib/Target/RISCV/VentusLegalizeLoad.cpp:121:15
#18 0x00007f72c4957d0a llvm::MachineFunctionPass::runOnFunction(llvm::Function&) /home/wuyang.nie/projects/ventus/llvm-project/llvm/lib/CodeGen/MachineFunctionPass.cpp:91:33
#19 0x00007f72bdd9cb58 llvm::FPPassManager::runOnFunction(llvm::Function&) /home/wuyang.nie/projects/ventus/llvm-project/llvm/lib/IR/LegacyPassManager.cpp:1430:20
#20 0x00007f72bdd9ce21 llvm::FPPassManager::runOnModule(llvm::Module&) /home/wuyang.nie/projects/ventus/llvm-project/llvm/lib/IR/LegacyPassManager.cpp:1476:13
#21 0x00007f72bdd9d293 (anonymous namespace)::MPPassManager::runOnModule(llvm::Module&) /home/wuyang.nie/projects/ventus/llvm-project/llvm/lib/IR/LegacyPassManager.cpp:1545:20
#22 0x00007f72bdd981b4 llvm::legacy::PassManagerImpl::run(llvm::Module&) /home/wuyang.nie/projects/ventus/llvm-project/llvm/lib/IR/LegacyPassManager.cpp:535:13
#23 0x00007f72bdd9db69 llvm::legacy::PassManager::run(llvm::Module&) /home/wuyang.nie/projects/ventus/llvm-project/llvm/lib/IR/LegacyPassManager.cpp:1673:1
#24 0x00007f72c5ad2458 (anonymous namespace)::EmitAssemblyHelper::RunCodegenPipeline(clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream>>&, std::unique_ptr<llvm::ToolOutputFile, std::default_delete<llvm::ToolOutputFile>>&) /home/wuyang.nie/projects/ventus/llvm-project/clang/lib/CodeGen/BackendUtil.cpp:1093:51
#25 0x00007f72c5ad2660 (anonymous namespace)::EmitAssemblyHelper::EmitAssembly(clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream>>) /home/wuyang.nie/projects/ventus/llvm-project/clang/lib/CodeGen/BackendUtil.cpp:1118:17
#26 0x00007f72c5ad36e6 clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::StringRef, llvm::Module*, clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream>>) /home/wuyang.nie/projects/ventus/llvm-project/clang/lib/CodeGen/BackendUtil.cpp:1274:25
#27 0x00007f72c62af11d clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) /home/wuyang.nie/projects/ventus/llvm-project/clang/lib/CodeGen/CodeGenAction.cpp:381:24
#28 0x00007f72b5b3b7d7 clang::ParseAST(clang::Sema&, bool, bool) /home/wuyang.nie/projects/ventus/llvm-project/clang/lib/Parse/ParseAST.cpp:203:14
#29 0x00007f72c27b4a6f clang::ASTFrontendAction::ExecuteAction() /home/wuyang.nie/projects/ventus/llvm-project/clang/lib/Frontend/FrontendAction.cpp:1162:11
#30 0x00007f72c62a8e08 clang::CodeGenAction::ExecuteAction() /home/wuyang.nie/projects/ventus/llvm-project/clang/lib/CodeGen/CodeGenAction.cpp:1170:5
#31 0x00007f72c27b432e clang::FrontendAction::Execute() /home/wuyang.nie/projects/ventus/llvm-project/clang/lib/Frontend/FrontendAction.cpp:1059:38
#32 0x00007f72c26c6109 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) /home/wuyang.nie/projects/ventus/llvm-project/clang/lib/Frontend/CompilerInstance.cpp:1045:42
#33 0x00007f72c75cf966 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) /home/wuyang.nie/projects/ventus/llvm-project/clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp:264:38
#34 0x0000563183abaaa1 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) /home/wuyang.nie/projects/ventus/llvm-project/clang/tools/driver/cc1_main.cpp:251:40
#35 0x0000563183aa8bca ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&) /home/wuyang.nie/projects/ventus/llvm-project/clang/tools/driver/driver.cpp:319:20
#36 0x00007f72c1ff0f69 clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const::'lambda'()::operator()() const /home/wuyang.nie/projects/ventus/llvm-project/clang/lib/Driver/Job.cpp:428:32
#37 0x00007f72c1ff1575 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const::'lambda'()>(long) /home/wuyang.nie/projects/ventus/llvm-project/llvm/include/llvm/ADT/STLFunctionalExtras.h:46:40
#38 0x00007f72bc920594 llvm::function_ref<void ()>::operator()() const /home/wuyang.nie/projects/ventus/llvm-project/llvm/include/llvm/ADT/STLFunctionalExtras.h:68:62
#39 0x00007f72bc934984 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) /home/wuyang.nie/projects/ventus/llvm-project/llvm/lib/Support/CrashRecoveryContext.cpp:434:10
#40 0x00007f72c1ff1187 clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const /home/wuyang.nie/projects/ventus/llvm-project/clang/lib/Driver/Job.cpp:428:7
#41 0x00007f72c1f74bf8 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const /home/wuyang.nie/projects/ventus/llvm-project/clang/lib/Driver/Compilation.cpp:200:22
#42 0x00007f72c1f74f86 clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const /home/wuyang.nie/projects/ventus/llvm-project/clang/lib/Driver/Compilation.cpp:254:62
#43 0x00007f72c1f8dacb clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) /home/wuyang.nie/projects/ventus/llvm-project/clang/lib/Driver/Driver.cpp:1816:28
#44 0x0000563183aaa196 clang_main(int, char**) /home/wuyang.nie/projects/ventus/llvm-project/clang/tools/driver/driver.cpp:520:39
#45 0x0000563183adcc5e main /home/wuyang.nie/projects/ventus/llvm-project/build/tools/clang/tools/driver/clang-driver.cpp:11:63
#46 0x00007f72bc212083 __libc_start_main /build/glibc-e2p3jK/glibc-2.31/csu/../csu/libc-start.c:342:3
#47 0x0000563183aa725e _start (/home/wuyang.nie/projects/ventus/llvm-project/install/bin/clang+0x4f25e)
clang-16: error: clang frontend command failed with exit code 134 (use -v to see invocation)
clang version 16.0.0 (https://github.com/THU-DSP-LAB/llvm-project.git 279251d31d6536f0c955ee6298c90b05021b934b)
Target: riscv32-unknown-unknown
Thread model: posix
InstalledDir: /home/wuyang.nie/projects/ventus/llvm-project/install/bin
clang-16: note: diagnostic msg: 
********************

**Comment by zhoujingya** [comment]
Solved by this [PR](https://github.com/THU-DSP-LAB/llvm-project/pull/118), you can check
