### ISSUE TITLE
[Bug] vload3/vstore3函数链接失败

### ISSUE THREAD

**Issue by Jules-Kong** [THU-DSP-LAB/llvm-project#150]
- 报错：

![image](https://github.com/user-attachments/assets/64a535c0-5af6-4de8-aef8-0aa75c7ae246)

![image](https://github.com/user-attachments/assets/0f9d33b2-07e0-47a2-a4ed-bbd2deafb751)

- 涉及到的用例：
CTS-geometrics：geom_length、geom_normalize    
CTS-select： 
select_uchar_uchar
select_uchar_char
select_char_uchar
select_char_char
select_ushort_ushort
select_ushort_short
select_short_ushort
select_short_short
select_half_ushort
select_half_short
select_uint_uint
select_uint_int
select_int_uint
select_int_int
select_float_uint
select_float_int

**Comment by Jules-Kong** [comment]
涉及到的用例还有 CTS-conversions；CTS-math_brute_force；

**Comment by ziliangzl** [comment]
这个pocl的日志是在哪里看啊

**Comment by Jules-Kong** [comment]
> 这个pocl的日志是在哪里看啊
设置 export POCL_DEBUG=all   
![91467b86318394db35c94bd1a49c2ce](https://github.com/user-attachments/assets/b620f122-9019-43cd-831a-9a567768bf61)

**Comment by ziliangzl** [comment]
将pocl回滚到https://github.com/THU-DSP-LAB/pocl/commit/bb151c0a65a055b82a881b173ed9b742359869fb 能够通过测试。
也就是说问题出在后面的一个commit中：https://github.com/THU-DSP-LAB/pocl/commit/fbbf1d2f1e55a489c4195c4f4036894777424e07
