### ISSUE TITLE
[Libclc] 一些库函数缺失

### ISSUE THREAD

**Issue by Jules-Kong** [THU-DSP-LAB/llvm-project#151]
- 用例： CTS-math_brute_force
- 复现方式：整体运行math_brute_force子测试套；
- 函数缺失包括：vload3/vstore3/fract/frexp/lgamma_r/modf/remquo/sincos

**Comment by ziliangzl** [comment]
与https://github.com/THU-DSP-LAB/llvm-project/issues/150 相同，已将问题定位到pocl。
