### ISSUE TITLE
[CTS] basic/if failed

### ISSUE THREAD

**Issue by guaguabao123** [THU-DSP-LAB/llvm-project#16]
1. run test_basic if  failed 
2. simple change  case to test
    A.  set 32 threads , run test_basic if 32
    B.   
![WXWorkLocal_16944375885891](https://github.com/THU-DSP-LAB/llvm-project/assets/70496385/ec4f9bf7-dcc6-4edf-b37c-8ecdb077226f)
3. run failed
    input data  has 0x1 ,but output data is 0x7fffffff
    
![WXWorkLocal_16944229622649](https://github.com/THU-DSP-LAB/llvm-project/assets/70496385/d647b845-8b5d-4027-8527-baec3040d35e)

**Comment by zhoujingya** [comment]
做了一些测试，看了一下spike的输出，发现有指令报访存指令的错误,看这个[链接](https://paste.ubuntu.com/p/VB5wmQTz7y/)

**Comment by zhoujingya** [comment]
发现core0的结果是对的，看这个[链接]( https://paste.ubuntu.com/p/DKFStgXkFR/)

**Comment by guaguabao123** [comment]
dump文件[https://paste.ubuntu.com/p/chZ87V4HPz/](url)
log文件[https://paste.ubuntu.com/p/Zw77bNjngJ/](url)

**Comment by zhoujingfighting** [comment]
目前总结得出，是软件这边的bug，得优化访存行为

**Comment by zhoujingya** [comment]
<img width="1197" alt="image" src="https://github.com/THU-DSP-LAB/llvm-project/assets/104264072/3d846776-9459-427d-913a-9b6474618e23">
确定是join指令这边出问题了

**Comment by zhoujingya** [comment]
__kernel void test_if(__global int *src, __global int *dst)
{
    int  tid = get_global_id(0);

    if (src[tid] == 0)
        dst[tid] = 0x12345678;
    else if (src[tid] == 1)
        dst[tid] = 0x23456781;
    else if (src[tid] == 2)
        dst[tid] = 0x34567812;
    else if (src[tid] == 3)
        dst[tid] = 0x45678123;
    else if (src[tid] == 4)
        dst[tid] = 0x56781234;
    else if (src[tid] == 5)
        dst[tid] = 0x67812345;
    else if (src[tid] == 6)
        dst[tid] = 0x78123456;
    else if (src[tid] == 7)
        dst[tid] = 0x81234567;
    else
        dst[tid] = 0x7FFFFFFF;

}

**Comment by zhoujingya** [comment]
之前的提交有点问题:https://github.com/THU-DSP-LAB/llvm-project/commit/4bfde6aa71c9f44778990bec81a3e18b6808a453

**Comment by zhoujingya** [comment]
solve by this commit 58e57e868b00411cb3717cc9f1479cd5bad670a9
