### ISSUE TITLE
error when run poclcc -l 

### ISSUE THREAD

**Issue by minisparrow** [THU-DSP-LAB/llvm-project#3]
CL_PLATFORM_NOT_FOUND_KHR in int main(int, char **) on line 289

**Comment by minisparrow** [comment]
> CL_PLATFORM_NOT_FOUND_KHR in int main(int, char **) on line 289

It did not detect the ventus gpu when i run poclcc, should i run this command in a FPGA platform or how to run it in a simulator?

**Comment by zhoujingya** [comment]
Run export LD_LIBRARY_PATH=<path_to>/ventus-llvm/install/lib to tell OpenCL application to use your own built libOpenCL.so, also to correctly locate LLVM shared libraries

Run export OCL_ICD_VENDORS=<path_to>/libpocl.so to tell ocl icd loader where the icd driver is.

Finally, run export POCL_DEVICES="ventus" to tell pocl driver which device is available

**Comment by zhoujingya** [comment]
> > CL_PLATFORM_NOT_FOUND_KHR in int main(int, char **) on line 289
> 
> It did not detect the ventus gpu when i run poclcc, should i run this command in a FPGA platform or how to run it in a simulator?

we are currently working to try to make an ELF file running in spike, soon or later, we will update , you can also check  `THU/isa-simulator` repository

**Comment by minisparrow** [comment]
> Run export LD_LIBRARY_PATH=<path_to>/ventus-llvm/install/lib to tell OpenCL application to use your own built libOpenCL.so, also to correctly locate LLVM shared libraries
> 
> Run export OCL_ICD_VENDORS=<path_to>/libpocl.so to tell ocl icd loader where the icd driver is.
> 
> Finally, run export POCL_DEVICES="ventus" to tell pocl driver which device is available

I export this variable and still has error. then I go to debug mode by export POCL_DEBUG=all, found that it cannot find the libpocl-devices-ventus.so in pocl/build/lib/CL/pocl/. after i copy file from install/lib/pocl mannully, it passed.

**Comment by minisparrow** [comment]
@zhoujingya  oh, it should export OCL_ICD_VENDORS the install/lib path while note pocl/build/lib. Thanks

**Comment by zhoujingya** [comment]
@minisparrow ok, I will colse this issue, welcome any other issues later
