### ISSUE TITLE
[CTS] parameter types简单参数的对齐

### ISSUE THREAD

**Issue by zhoujingya** [THU-DSP-LAB/llvm-project#39]

**Comment by zhoujingya** [comment]
不考虑double数据类型的对齐，目前pocl是已经处理完毕了

**Comment by zhoujingya** [comment]
```
kernel void test_kernel(
char c, uchar uc, short s, ushort us, int i, uint ui, float f,
global float *result)
{

result[0] =  (c);
result[1] =  (uc);
result[2] =  (s);
result[3] =  (us);
result[4] =  (i);
result[5] =  (ui);
result[6] = f;
}
```
simple test codes

**Comment by Jules-Kong** [comment]
- the more complex testcase

''' 
   __kernel void test_kernel(
    char16 c, uchar16 uc, short16 s, ushort16 us, int16 i, uint16 ui, float16 f,
    __global float16 *result)
    {
        result[0] = convert_float16(c);
        result[1] = convert_float16(uc);
        result[2] = convert_float16(s);
        result[3] = convert_float16(us);
        result[4] = convert_float16(i);
        result[5] = convert_float16(ui);
        result[6] = f;
    }
'''
