### ISSUE TITLE
回退vsub12.v指令提交后回归local_arg_def case出错

### ISSUE THREAD

**Issue by lifeiabc** [THU-DSP-LAB/llvm-project#46]
在回退提交https://github.com/THU-DSP-LAB/llvm-project/commit/0e5eef6abb07b56e0090210c7fd5f7f3e0cd4124 ，vlw12.v会从错误的内存地址上load数据，具体的log如下：
[log_arg_def.dump.txt](https://github.com/THU-DSP-LAB/llvm-project/files/13160842/log_arg_def.dump.txt)
[local_arg_def.log](https://github.com/THU-DSP-LAB/llvm-project/files/13160843/local_arg_def.log)

**Comment by lifeiabc** [comment]
[local_arg_def_pass.log](https://github.com/THU-DSP-LAB/llvm-project/files/13161013/local_arg_def_pass.log)
[log_arg_def_pass.txt](https://github.com/THU-DSP-LAB/llvm-project/files/13161014/log_arg_def_pass.txt)
[local_arg_def_pass.dump.txt](https://github.com/THU-DSP-LAB/llvm-project/files/13161019/local_arg_def_pass.dump.txt)

**Comment by zhoujingya** [comment]
Actually this regression fault is not caused by the [commit](https://github.com/THU-DSP-LAB/llvm-project/commit/0e5eef6abb07b56e0090210c7fd5f7f3e0cd4124) above
