### ISSUE TITLE
在去掉vsub12.v指令后kernel_call_kernel_function fail

### ISSUE THREAD

**Issue by lifeiabc** [THU-DSP-LAB/llvm-project#62]
在去掉vsub12.v指令后kernel_call_kernel_function fail，有vsub12.v时case pass。

**Comment by zhoujingya** [comment]
> 在去掉vsub12.v指令后kernel_call_kernel_function fail，有vsub12.v时case pass。

之前讨论过这个问题了， 貌似是spike vadd12.vi指令无符号数计算得有问题

**Comment by zhoujingya** [comment]
> > 在去掉vsub12.v指令后kernel_call_kernel_function fail，有vsub12.v时case pass。
> 
> 之前讨论过这个问题了， 貌似是spike vadd12.vi指令无符号数计算得有问题
在本地上删除vsub12.vi指令的定义与指令匹配之后，这个样例跑的是没有问题的，能提供具体的仓库版本吗？llvm pocl spike driver？

**Comment by lifeiabc** [comment]
在terapines-dev branch上试了下是可以的
