### ISSUE TITLE
支持regpair指令和regpairi指令的生成

### ISSUE THREAD

**Issue by wangqinfan** [THU-DSP-LAB/llvm-project#94]
目前需要扩展64位寻址和计算，在需要扩展64位计算和寻址指令的前面插入regpair指令和regpairi指令来表示下一条指令需要扩展，所以这里编译器需要先在后端中定义这两条指令，指令格式如下：

**Comment by wangqinfan** [comment]
![微信图片_20240119115657](https://github.com/THU-DSP-LAB/llvm-project/assets/94455844/3b1f4205-649f-4181-a606-2454bafb919b)
![微信图片_20240119115702](https://github.com/THU-DSP-LAB/llvm-project/assets/94455844/54013855-6b6d-4f29-8061-592ea4607ee4)

**Comment by zhoujingya** [comment]
No later support
